// Accounting Integrity audit
(function(){
  const originalDeleteTxn=window.deleteTxn;
  window.deleteTxn=function(id){const tx=transactions.find(x=>x.id===id);if(tx&&(tx.debtId||tx.receivableId)){alert('Linked special transactions must be managed from Debts or Receivables.');return;}return originalDeleteTxn(id)};
  function audit(){
    const issues=[],warnings=[],expected={}; const add=(a,m)=>(a==='i'?issues:warnings).push(m);
    const seen=new Set(); accounts.forEach(a=>{if(seen.has(a.id))add('i',`Duplicate account ID: ${a.id}`);seen.add(a.id);if(!a.name)add('i','An account has no name.')});
    transactions.forEach(x=>{
      if(!x.id)add('i','A transaction has no ID.');
      if(x.amount==null||Number.isNaN(+x.amount)||+x.amount<0)add('i',`Invalid amount in transaction ${x.id||'(unknown)'}.`);
      if(['income','expense','opening'].includes(x.type)){if(!getAccount(x.account))add('i',`Transaction ${x.id} points to a missing account.`)}
      else if(x.type==='transfer'){if(!getAccount(x.from)||!getAccount(x.to))add('i',`Transfer ${x.id} points to a missing account.`);if(x.from===x.to)add('i',`Transfer ${x.id} uses the same account twice.`)}
      else add('w',`Transaction ${x.id} has unknown type ${x.type}.`);
      if(x.debtId){const d=debts.find(d=>d.id===x.debtId);if(!d)add('i',`Debt payment ${x.id} points to a missing debt.`);else if(x.type!=='expense'||x.category!=='Debt Payment')add('i',`Linked debt payment ${x.id} is not an Expense / Debt Payment.`)}
      if(x.receivableId){const r=receivables.find(r=>r.id===x.receivableId);if(!r)add('i',`Receivable transaction ${x.id} points to a missing receivable.`);else if(!['income','expense'].includes(x.type))add('i',`Linked receivable transaction ${x.id} has an invalid type.`)}
    });
    const opens={};transactions.filter(x=>x.type==='opening').forEach(x=>(opens[x.account]??=[]).push(x));Object.entries(opens).forEach(([k,v])=>{if(v.length>1)add('w',`${getAccount(k)?.name||k} has ${v.length} opening-balance records.`)});
    debts.forEach(d=>{const paid=transactions.filter(x=>x.debtId===d.id&&x.type==='expense').reduce((s,x)=>s+ +x.amount,0),e=Math.max(0,+d.original-paid);if(Math.abs(e-(+d.balance||0))>.001)add('i',`Debt ${d.name} shows ${money(d.balance)} but linked payments imply ${money(e)}.`)});
    receivables.forEach(r=>{const paid=rTx.filter(t=>t.receivableId===r.id&&t.type==='payment').reduce((s,t)=>s+ +t.amount,0),e=Math.max(0,+r.original-paid);if(Math.abs(e-(+r.balance||0))>.001)add('i',`Receivable ${r.person} shows ${money(r.balance)} but payments imply ${money(e)}.`);rTx.filter(t=>t.receivableId===r.id&&t.type==='payment').forEach(t=>{if(!getAccount(t.account))add('i',`Receivable payment ${t.id} points to a missing account.`)})});
    accounts.forEach(a=>expected[a.id]=0);const latest={};transactions.filter(x=>x.type==='opening').forEach(x=>{if(!latest[x.account]||String(x.date)>String(latest[x.account].date))latest[x.account]=x});Object.values(latest).forEach(x=>{const a=getAccount(x.account);if(a)expected[a.id]=+x.amount});
    transactions.filter(x=>x.type!=='opening').forEach(x=>{if(x.type==='income'){const a=getAccount(x.account);if(a)expected[a.id]+=+x.amount}else if(x.type==='expense'){const a=getAccount(x.account);if(a)expected[a.id]-=+x.amount}else if(x.type==='transfer'){const f=getAccount(x.from),t=getAccount(x.to);if(f)expected[f.id]-=+x.amount;if(t)expected[t.id]+=+x.amount}});
    accounts.forEach(a=>{if(Math.abs((+a.balance||0)-expected[a.id])>.001)add('i',`${a.name} is ${money(a.balance)} but the ledger calculates ${money(expected[a.id])}.`)});
    transactions.filter(x=>x.category==='Debt Payment'&&!x.debtId).forEach(x=>add('w',`Unlinked Debt Payment: ${x.date} · ${money(x.amount)}.`));transactions.filter(x=>x.category==='Money Lent'&&!x.receivableId).forEach(x=>add('w',`Unlinked Money Lent: ${x.date} · ${money(x.amount)}.`));transactions.filter(x=>x.category==='Receivable Payment'&&!x.receivableId).forEach(x=>add('w',`Unlinked Receivable Payment: ${x.date} · ${money(x.amount)}.`));
    return{issues,warnings,expected};
  }
  function page(){const a=audit(),ok=!a.issues.length;const rows=accounts.map(x=>{const m=Math.abs((+x.balance||0)-a.expected[x.id])<.001;return`<tr><td>${esc(x.name)}</td><td>${money(x.balance)}</td><td>${money(a.expected[x.id])}</td><td class="${m?'positive':'negative'}">${m?'MATCH':'DIFFERENT'}</td></tr>`}).join('');const problems=[...a.issues.map(x=>`<div class="account" style="border-color:#7f1d1d"><b class="negative">Issue</b><div class="debt-meta" style="margin-top:6px">${esc(x)}</div></div>`),...a.warnings.map(x=>`<div class="account" style="border-color:#854d0e"><b class="warning">Warning</b><div class="debt-meta" style="margin-top:6px">${esc(x)}</div></div>`)].join('');document.getElementById('content').innerHTML=`<div class="cards"><div class="card"><div class="label">Integrity</div><div class="value ${ok?'positive':'negative'}" style="font-size:20px">${ok?'✓ Consistent':'⚠ Needs attention'}</div></div><div class="card"><div class="label">Issues</div><div class="value ${a.issues.length?'negative':'positive'}">${a.issues.length}</div></div><div class="card"><div class="label">Warnings</div><div class="value ${a.warnings.length?'warning':'positive'}">${a.warnings.length}</div></div><div class="card"><div class="label">Transactions Checked</div><div class="value">${transactions.length}</div></div></div><div class="section"><div class="section-head"><div><h2>Account Reconciliation</h2><div class="muted" style="margin-top:5px">Stored balance compared with an independent ledger calculation.</div></div><button class="btn secondary" onclick="integrityRebuild()">Rebuild & Verify</button></div><div class="table-wrap"><table><thead><tr><th>Account</th><th>Stored</th><th>Calculated</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></div><div class="section"><div class="section-head"><h2>Integrity Checks</h2></div><div class="accounts">${problems||'<div class="empty">Everything checked out. 🎉</div>'}</div></div>`}
  window.integrityAudit=audit;window.integrityRebuild=function(){if(!confirm('Rebuild account, debt, and receivable balances from existing records? This does not delete transactions.'))return;rebuild();page();toast('Balances rebuilt from the ledger')};
  const navEl=document.querySelector('.nav');if(navEl&&!navEl.querySelector('[data-page="integrity"]')){const b=document.createElement('button');b.dataset.page='integrity';b.textContent='Integrity';navEl.appendChild(b)}const oldNav=window.nav;window.nav=function(p){if(p==='integrity'){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));document.getElementById('pageTitle').textContent='Integrity';return page()}return oldNav(p)};navEl?.querySelector('[data-page="integrity"]')?.addEventListener('click',()=>window.nav('integrity'));
})();
